@startuml
package "main" {
class Hanged
}

package "views"{
abstract class View
    package "console" {
        class StartView
        class InGameView
    }
}

package "controllers"{
class Logic
enum SesionValue
abstract class Controller
class StartController
class ProposedWordController{
- Word word

+ findCharacterInWord(char) : char[]
}
class EndController


}


package "models" {
class Word{
- String word
+ getLengthWord() : int
+ getWord() : String
}
class HangedPart{
}
class Turn
class Player
class BoardPaper
}
Hanged *--> View
Hanged *--> Logic
Logic o--> Controller
View <|-- StartView
View <|-- InGameView

Controller <|-- StartController
Controller <|-- ProposedWordController
Controller <|-- ProposedCharController
Controller <|-- EndController

Logic o--> SesionValue



@enduml